### ISSUE TITLE
~/.config/fish/conf.d/insulter.fish (line 80): $(...) is not supported. In fish, please use '(random)'.

### ISSUE THREAD

**Issue by Mr-MyDooM** [asteroidalaz/fish-insulter#5]
I am getting this error after installing 

```
fisher install version 4.4.4
Fetching https://api.github.com/repos/alaz-oz/fish-insulter/tarball/HEAD
Installing alaz-oz/fish-insulter
           /home/mj/.config/fish/conf.d/insulter.fish
~/.config/fish/conf.d/insulter.fish (line 80): $(...) is not supported. In fish, please use '(random)'.
	set RANDOM $(random)
	           ^
from sourcing file ~/.config/fish/conf.d/insulter.fish
	called on line 189 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install Alaz-Oz/fish-insulter'
source: Error while reading file “/home/path/.config/fish/conf.d/insulter.fish”
Installed 1 plugin/s

```

when i run new terminal i am getting this message 

```
~/.config/fish/conf.d/insulter.fish (line 80): $(...) is not supported. In fish, please use '(random)'.
	set RANDOM $(random)
	           ^
from sourcing file ~/.config/fish/conf.d/insulter.fish
	called on line 253 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
	called during startup
source: Error while reading file “/home/path/.config/fish/conf.d/insulter.fish”
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

**Comment by Alaz-Oz** [comment]
Could you give more details,
- OS
- fish version
- fish config (~/.config/fish/config.fish)

Are you running fish shell in some kind of debug mode? As I am not getting these warnings on my computer.

**Comment by Alaz-Oz** [comment]
Feel free to reopen this issue if the problem persist.

**Comment by Mr-MyDooM** [comment]
> Could you give more details,
> 
>     * OS
> 
>     * fish version
> 
>     * fish config (~/.config/fish/config.fish)
> 
> 
> Are you running fish shell in some kind of debug mode? As I am not getting these warnings on my computer.

lsb_release -a                                             (base) 0 (0.003s)
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

fish -v                                                    (base) 0 (0.078s)
fish, version 3.3.1

i am not running fish in any debug mode.

**Comment by Alaz-Oz** [comment]
@mydoom2010 Is it working fine? Or you are still getting errors?
